/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_jairosierra;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jairo Sierra
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jmi_crearmazo.setEnabled(false);
        jmi_crearcarta.setEnabled(false);
        jmi_agregarmazo.setEnabled(false);
        jmi_crearclan.setEnabled(false);
        jmi_agregarclan.setEnabled(false);
        jmi_verclan.setEnabled(false);
        jmi_vercartas.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearusa = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_nombreusa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_contrasena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jb_crear = new javax.swing.JButton();
        jb_color = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pf_passpord = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        jd_crearmazo = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jt_coste = new javax.swing.JTextField();
        cb_carta1 = new javax.swing.JComboBox<>();
        cb_carta2 = new javax.swing.JComboBox<>();
        cb_carta3 = new javax.swing.JComboBox<>();
        jb_crearmazo = new javax.swing.JButton();
        jd_crearcarta = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jt_dano = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jt_puntos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jt_nombre2 = new javax.swing.JTextField();
        jd_agregarmazo = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_usuarios1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cb_mazo1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cb_mazo2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        cb_mazo3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jd_crearclan = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jt_nombreclan = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jd_fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        cb_clantipo = new javax.swing.JComboBox<>();
        jb_clancrear = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        cb_lider = new javax.swing.JComboBox<>();
        jd_agregaralclan = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cb_clanes = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cb_usuarios2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jd_amigos_clan = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_lista1 = new javax.swing.JList<>();
        jLabel35 = new javax.swing.JLabel();
        cb_clanes1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jd_vercartas = new javax.swing.JDialog();
        jLabel36 = new javax.swing.JLabel();
        cb_mazos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_cartas = new javax.swing.JTree();
        jButton5 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        cb_usuarios5 = new javax.swing.JComboBox<>();
        menu_pop = new javax.swing.JPopupMenu();
        jmi_ver = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        Crear = new javax.swing.JMenu();
        jmi_crear = new javax.swing.JMenuItem();
        Usuarios = new javax.swing.JMenu();
        jmi_login = new javax.swing.JMenuItem();
        jmi_crearmazo = new javax.swing.JMenuItem();
        jmi_crearcarta = new javax.swing.JMenuItem();
        jmi_agregarmazo = new javax.swing.JMenuItem();
        jmi_crearclan = new javax.swing.JMenuItem();
        jmi_agregarclan = new javax.swing.JMenuItem();
        jmi_verclan = new javax.swing.JMenuItem();
        jmi_vercartas = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Nombre de usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Color favorito");

        jb_crear.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jb_crear.setText("Crear");
        jb_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearActionPerformed(evt);
            }
        });

        jb_color.setText("Color");
        jb_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearusaLayout = new javax.swing.GroupLayout(jd_crearusa.getContentPane());
        jd_crearusa.getContentPane().setLayout(jd_crearusaLayout);
        jd_crearusaLayout.setHorizontalGroup(
            jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearusaLayout.createSequentialGroup()
                .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearusaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombre)
                            .addComponent(jt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGap(189, 189, 189)
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_color)))
                    .addGroup(jd_crearusaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_nombreusa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_crearusaLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jb_crear))
                    .addGroup(jd_crearusaLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jd_crearusaLayout.setVerticalGroup(
            jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearusaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearusaLayout.createSequentialGroup()
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jb_color))
                        .addGap(21, 21, 21)
                        .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_nombreusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_crearusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_crear)
                .addGap(87, 87, 87))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Ingresar al Sistema");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña");

        ingresar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel8))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(75, 75, 75)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_passpord, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_user))))
                .addGap(265, 265, 265))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pf_passpord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Crear Mazo");

        jLabel12.setText("Carta 1");

        jLabel13.setText("Carta 2");

        jLabel14.setText("Carta 3");

        jLabel15.setText("Coste");

        cb_carta1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_carta1ItemStateChanged(evt);
            }
        });

        jb_crearmazo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jb_crearmazo.setText("Crear");
        jb_crearmazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearmazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearmazoLayout = new javax.swing.GroupLayout(jd_crearmazo.getContentPane());
        jd_crearmazo.getContentPane().setLayout(jd_crearmazoLayout);
        jd_crearmazoLayout.setHorizontalGroup(
            jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearmazoLayout.createSequentialGroup()
                .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_crearmazo)
                    .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_crearmazoLayout.createSequentialGroup()
                            .addGap(288, 288, 288)
                            .addComponent(jLabel11))
                        .addGroup(jd_crearmazoLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_crearmazoLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(49, 49, 49)
                                    .addComponent(jt_coste, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_crearmazoLayout.createSequentialGroup()
                                    .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addGap(97, 97, 97)
                                    .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_carta1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_carta2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_carta3, 0, 128, Short.MAX_VALUE)))))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jd_crearmazoLayout.setVerticalGroup(
            jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearmazoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(46, 46, 46)
                .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_carta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearmazoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13))
                    .addGroup(jd_crearmazoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(cb_carta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_carta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_crearmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jb_crearmazo)
                .addGap(27, 27, 27))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setText("Crear Carta");

        jLabel17.setText("Daño");

        jLabel18.setText("Puntos de vida");

        jLabel19.setText("Tipo");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Golem", "Leñador", "Dragon Infernal", "Dragon", "Gigante Noble", "Pandilla de duentes", " " }));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Nombre");

        javax.swing.GroupLayout jd_crearcartaLayout = new javax.swing.GroupLayout(jd_crearcarta.getContentPane());
        jd_crearcarta.getContentPane().setLayout(jd_crearcartaLayout);
        jd_crearcartaLayout.setHorizontalGroup(
            jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearcartaLayout.createSequentialGroup()
                        .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearcartaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jt_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(321, Short.MAX_VALUE))
                    .addGroup(jd_crearcartaLayout.createSequentialGroup()
                        .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel19)))
                        .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jt_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jd_crearcartaLayout.setVerticalGroup(
            jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addGap(64, 64, 64)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jt_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jt_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setText("Agregar Mazo");

        jLabel22.setText("Usuarios");

        jLabel23.setText("Mazo 1");

        jLabel24.setText("Mazo 2");

        jLabel25.setText("Mazo 3");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarmazoLayout = new javax.swing.GroupLayout(jd_agregarmazo.getContentPane());
        jd_agregarmazo.getContentPane().setLayout(jd_agregarmazoLayout);
        jd_agregarmazoLayout.setHorizontalGroup(
            jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarmazoLayout.createSequentialGroup()
                .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_agregarmazoLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel21))
                    .addGroup(jd_agregarmazoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(156, 156, 156)
                        .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_usuarios1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_mazo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_mazo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_mazo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_agregarmazoLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton2)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jd_agregarmazoLayout.setVerticalGroup(
            jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarmazoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel21)
                .addGap(45, 45, 45)
                .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cb_mazo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cb_mazo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_agregarmazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(cb_mazo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setText("Crear Clan");

        jLabel27.setText("Nombre");

        jLabel28.setText("Fecha de creacion");

        jLabel29.setText("Tipo");

        cb_clantipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Planta", "Oro", "Legendario", " " }));

        jb_clancrear.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jb_clancrear.setText("Crear");
        jb_clancrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clancrearActionPerformed(evt);
            }
        });

        jLabel30.setText("Usuario Lider");

        javax.swing.GroupLayout jd_crearclanLayout = new javax.swing.GroupLayout(jd_crearclan.getContentPane());
        jd_crearclan.getContentPane().setLayout(jd_crearclanLayout);
        jd_crearclanLayout.setHorizontalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearclanLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(cb_lider, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jd_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jd_crearclanLayout.createSequentialGroup()
                                    .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel29))
                                    .addGap(62, 62, 62)
                                    .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_clantipo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26)
                                            .addComponent(jt_nombreclan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jb_clancrear)))
                .addGap(228, 228, 228))
        );
        jd_crearclanLayout.setVerticalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel26)
                .addGap(25, 25, 25)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb_lider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jt_nombreclan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jd_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(65, 65, 65)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(cb_clantipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jb_clancrear)
                .addContainerGap())
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel31.setText("Agregar Al Clan");

        jLabel32.setText("Clan");

        jLabel33.setText("Usuarios");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregaralclanLayout = new javax.swing.GroupLayout(jd_agregaralclan.getContentPane());
        jd_agregaralclan.getContentPane().setLayout(jd_agregaralclanLayout);
        jd_agregaralclanLayout.setHorizontalGroup(
            jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                .addGroup(jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel31))
                    .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                        .addGroup(jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel32))
                            .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel33)))
                        .addGap(71, 71, 71)
                        .addGroup(jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_usuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_clanes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton3)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jd_agregaralclanLayout.setVerticalGroup(
            jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregaralclanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel31)
                .addGap(57, 57, 57)
                .addGroup(jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(cb_clanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jd_agregaralclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_usuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(68, 68, 68))
        );

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel34.setText("Miembros del clan");

        jScrollPane1.setViewportView(jl_lista1);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setText("Clanes");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setText("Ver");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_amigos_clanLayout = new javax.swing.GroupLayout(jd_amigos_clan.getContentPane());
        jd_amigos_clan.getContentPane().setLayout(jd_amigos_clanLayout);
        jd_amigos_clanLayout.setHorizontalGroup(
            jd_amigos_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_amigos_clanLayout.createSequentialGroup()
                .addGroup(jd_amigos_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_amigos_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_amigos_clanLayout.createSequentialGroup()
                            .addGap(347, 347, 347)
                            .addComponent(jLabel34))
                        .addGroup(jd_amigos_clanLayout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jLabel35)
                            .addGap(61, 61, 61)
                            .addComponent(cb_clanes1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_amigos_clanLayout.createSequentialGroup()
                            .addGap(342, 342, 342)
                            .addComponent(jButton4))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jd_amigos_clanLayout.setVerticalGroup(
            jd_amigos_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_amigos_clanLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel34)
                .addGap(49, 49, 49)
                .addGroup(jd_amigos_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_clanes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jLabel36.setText("Mazo");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cartas");
        jt_cartas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_cartas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cartasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_cartas);

        jButton5.setText("Agregar al arbol");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel37.setText("Usuarios");

        javax.swing.GroupLayout jd_vercartasLayout = new javax.swing.GroupLayout(jd_vercartas.getContentPane());
        jd_vercartas.getContentPane().setLayout(jd_vercartasLayout);
        jd_vercartasLayout.setHorizontalGroup(
            jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_vercartasLayout.createSequentialGroup()
                .addGroup(jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_vercartasLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_vercartasLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton5))
                    .addGroup(jd_vercartasLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(110, 110, 110)
                        .addGroup(jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_mazos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_usuarios5, 0, 121, Short.MAX_VALUE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jd_vercartasLayout.setVerticalGroup(
            jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_vercartasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cb_usuarios5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jd_vercartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cb_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jmi_ver.setText("Ver la informacion de la carta");
        jmi_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verActionPerformed(evt);
            }
        });
        menu_pop.add(jmi_ver);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Crear.setText("Crear Usuario");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        jmi_crear.setText("Crear Usuario");
        jmi_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearActionPerformed(evt);
            }
        });
        Crear.add(jmi_crear);

        jMenuBar1.add(Crear);

        Usuarios.setText("Usuarios");

        jmi_login.setText("Login");
        jmi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_loginActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_login);

        jmi_crearmazo.setText("Crear Mazo");
        jmi_crearmazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearmazoActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_crearmazo);

        jmi_crearcarta.setText("Crear Carta");
        jmi_crearcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearcartaActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_crearcarta);

        jmi_agregarmazo.setText("Agregar Mazo");
        jmi_agregarmazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarmazoActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_agregarmazo);

        jmi_crearclan.setText("Crear Clan");
        jmi_crearclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearclanActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_crearclan);

        jmi_agregarclan.setText("Agregar al clan");
        jmi_agregarclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarclanActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_agregarclan);

        jmi_verclan.setText("Ver en el clan");
        jmi_verclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verclanActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_verclan);

        jmi_vercartas.setText("Ver las cartas de un maso");
        jmi_vercartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_vercartasActionPerformed(evt);
            }
        });
        Usuarios.add(jmi_vercartas);

        jMenuBar1.add(Usuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearActionPerformed

    private void jmi_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearActionPerformed
        // TODO add your handling code here:
        jd_crearusa.setModal(true);
        jd_crearusa.pack();
        jd_crearusa.setLocationRelativeTo(this);
        jd_crearusa.setVisible(true);
    }//GEN-LAST:event_jmi_crearActionPerformed

    private void jb_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorMouseClicked
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Seleccione un color", Color.yellow);// a esta variable se le asigan el color que se selecciona
        jb_color.setBackground(c);//colorea el jl_Texto
    }//GEN-LAST:event_jb_colorMouseClicked

    private void jmi_crearmazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearmazoActionPerformed
        // TODO add your handling code here:
        jd_crearmazo.setModal(true);
        jd_crearmazo.pack();
        jd_crearmazo.setLocationRelativeTo(this);
        jd_crearmazo.setVisible(true);
    }//GEN-LAST:event_jmi_crearmazoActionPerformed

    private void jmi_crearcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearcartaActionPerformed
        // TODO add your handling code here:
        jd_crearcarta.setModal(true);
        jd_crearcarta.pack();
        jd_crearcarta.setLocationRelativeTo(this);
        jd_crearcarta.setVisible(true);
    }//GEN-LAST:event_jmi_crearcartaActionPerformed

    private void jb_crearmazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearmazoActionPerformed
        // TODO add your handling code here:
        double coste;
        coste = Double.parseDouble(jt_coste.getText());
        Mazos x = new Mazos(coste);
        Carta e = (Carta)cb_carta1.getSelectedItem();
        Carta e2 = (Carta)cb_carta2.getSelectedItem();
        Carta e3 = (Carta)cb_carta3.getSelectedItem();
        ArrayList<Carta> cartas = new ArrayList();
        cartas.add(e);
        cartas.add(e2);
        cartas.add(e3);
        x.setCartas(cartas);
        lista1.add(x);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_mazo1.getModel();
        modelo.addElement(x);
        cb_mazo1.setModel(modelo);
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_mazo2.getModel();
        modelo1.addElement(x);
        cb_mazo2.setModel(modelo1);
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_mazo3.getModel();
        modelo2.addElement(x);
        cb_mazo3.setModel(modelo2);
    }//GEN-LAST:event_jb_crearmazoActionPerformed

    private void jmi_agregarmazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarmazoActionPerformed
        // TODO add your handling code here:
        jd_agregarmazo.setModal(true);
        jd_agregarmazo.pack();
        jd_agregarmazo.setLocationRelativeTo(this);
        jd_agregarmazo.setVisible(true);
    }//GEN-LAST:event_jmi_agregarmazoActionPerformed

    private void jmi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_loginActionPerformed
        // TODO add your handling code here:
        hola();
    }//GEN-LAST:event_jmi_loginActionPerformed

    private void jb_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearActionPerformed
        // TODO add your handling code here:
        String nombre;
        String apellido;
        String usuario;
        String contrasena;
        Date fecha;
        int edad;
        Color color;
            nombre = jt_nombre.getText();
            apellido = jt_apellido.getText();
            usuario = jt_nombreusa.getText();
            contrasena = jt_contrasena.getText();
            fecha = jd_fecha.getDate();
            edad = (int) (((new Date()).getTime() - fecha.getTime()) / (1000 * 60 * 60 * 24) / 365);
            color = jb_color.getBackground();
            Usuarios x = new Usuarios(nombre, apellido, usuario, contrasena, fecha, edad, color);
            lista.add(x);
            JOptionPane.showMessageDialog(this, "Se agrego Correctamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_usuarios1.getModel();
        modelo.addElement(x);
        cb_usuarios1.setModel(modelo);
        cb_lider.setModel(modelo);
        cb_usuarios2.setModel(modelo);
        cb_usuarios5.setModel(modelo);
            jt_nombre.setText("");
            jt_apellido.setText("");
            jt_nombreusa.setText("");
            jt_contrasena.setText("");
            jd_fecha.setDate(new Date());
            jb_color.setBackground(Color.RED);
    }//GEN-LAST:event_jb_crearActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < lista.size(); i++) {
        if (tf_user.getText().equals(((Usuarios)lista.get(i)).getUsuario()) && pf_passpord.getText().equals(((Usuarios)lista.get(i)).getContrasena())) {
            jmi_login.setEnabled(false);
            jmi_crearmazo.setEnabled(true);
            jmi_crearcarta.setEnabled(true);
            jmi_agregarmazo.setEnabled(true);
            jmi_crearclan.setEnabled(true);
            jmi_agregarclan.setEnabled(true);
            jmi_verclan.setEnabled(true);
            jmi_vercartas.setEnabled(true);
            tf_user.setText("");
            pf_passpord.setText("");
            jd_login.setVisible(false);
        }
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = "";
        String dano;
        String vida;
        String objetivo = "";
        String velocidad = "";
        String elixir = "";
        dano = jt_dano.getText();
        vida = jt_puntos.getText();
        nombre = jt_nombre2.getText();
        Carta x = new Carta();
        if (cb_tipo.getSelectedItem().toString().equals("Minipekka")) {
            x = new Minipekka(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Montapuerco")) {
            x = new Montapuerco(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Golem")) {
            x = new Golem(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Leñador")) {
            x = new Lenador(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Dragon Infernal")) {
            x = new Dragon_Infernal(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Dragon")) {
            x = new Dragon(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Gigante Noble")) {
            x = new Gigante_Noble(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        if (cb_tipo.getSelectedItem().toString().equals("Pandilla de duendes")) {
            x = new Pandilla_Duendes(nombre, dano, vida, objetivo, velocidad, elixir);
        }
        jt_dano.setText("");
        jt_puntos.setText("");
        cb_tipo.setSelectedIndex(0);
        lista2.add(x);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_carta1.getModel();
        modelo.addElement(x);
        cb_carta1.setModel(modelo);
        DefaultComboBoxModel modelos = (DefaultComboBoxModel) cb_carta2.getModel();
        modelos.addElement(x);
        cb_carta2.setModel(modelos);
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_carta3.getModel();
        modelo2.addElement(x);
        cb_carta3.setModel(modelo2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = cb_usuarios1.getSelectedIndex();
        Mazos e1 = (Mazos)cb_mazo1.getSelectedItem();
        Mazos e2 = (Mazos)cb_mazo2.getSelectedItem();
        Mazos e3 = (Mazos)cb_mazo3.getSelectedItem();
        ArrayList<Mazos> mazo = new ArrayList();
        mazo.add(e1);
        mazo.add(e2);
        mazo.add(e3);
        lista.get(x).setMazo(mazo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jb_clancrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clancrearActionPerformed
        // TODO add your handling code here:
        String nombre;
   Date fecha;
    Usuarios lider;
    String tipo="";
    nombre = jt_nombreclan.getText();
    fecha = jd_fecha1.getDate();
    lider = (Usuarios)cb_lider.getSelectedItem();
    if(cb_clantipo.getSelectedItem().toString().equals("Bronce")){
        tipo="Bronce";
    }
    if(cb_clantipo.getSelectedItem().toString().equals("Oro")){
        tipo="Oro";
    }
    if(cb_clantipo.getSelectedItem().toString().equals("Legendario")){
        tipo="Legendario";
    }
    else{
        tipo="Plata";
    }
    Clan x = new Clan(nombre,fecha,lider,tipo);
    lista3.add(x);
    DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_clanes.getModel();
        modelo.addElement(x);
        cb_clanes.setModel(modelo);
    }//GEN-LAST:event_jb_clancrearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int x = cb_clanes.getSelectedIndex();
        int x1 = cb_usuarios2.getSelectedIndex();
        Usuarios x2 = (Usuarios)lista.get(x1);
        ArrayList<Usuarios> e = new ArrayList();
        e.add(x2);
        lista3.get(x).setMiembros(e);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jmi_crearclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearclanActionPerformed
        // TODO add your handling code here:
        jd_crearclan.setModal(true);
        jd_crearclan.pack();
        jd_crearclan.setLocationRelativeTo(this);
        jd_crearclan.setVisible(true);
    }//GEN-LAST:event_jmi_crearclanActionPerformed

    private void jmi_agregarclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarclanActionPerformed
        // TODO add your handling code here:
        jd_agregaralclan.setModal(true);
        jd_agregaralclan.pack();
        jd_agregaralclan.setLocationRelativeTo(this);
        jd_agregaralclan.setVisible(true);
    }//GEN-LAST:event_jmi_agregarclanActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_lista1.getModel();
        int x = cb_clanes.getSelectedIndex();
        lista3.get(x).getMiembros();
        modelo.addElement(lista3.get(x).getMiembros());
        jl_lista1.setModel(modelo);
    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_carta1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_carta1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_carta1ItemStateChanged

    private void jmi_verclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verclanActionPerformed
        // TODO add your handling code here:
        jd_amigos_clan.setModal(true);
        jd_amigos_clan.pack();
        jd_amigos_clan.setLocationRelativeTo(this);
        jd_amigos_clan.setVisible(true);
    }//GEN-LAST:event_jmi_verclanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       int w = cb_usuarios5.getSelectedIndex();
       ArrayList<Mazos> mazo = lista.get(w).getMazo();
       DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_mazos.getModel();
        modelo.addElement(mazo);
        cb_mazos.setModel(modelo);
       if(cb_mazos.getSelectedIndex()>=0){
           DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_cartas.getModel();
           DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modeloArbol.getRoot();
           String tipo="",nombre="";
           String dano,vida;
           dano=((Carta)lista2.get(cb_mazos.getSelectedIndex())).getDano();
           vida = ((Carta)lista2.get(cb_mazos.getSelectedIndex())).getVida();
           nombre = ((Carta)lista2.get(cb_mazos.getSelectedIndex())).getNombre();
           if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Minipekka")){
               tipo="Especial";
           }
           if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")){
               tipo="Especial";
           }
           if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Golem")){
           tipo="Epica";
       }
          if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Lenador")){
              tipo="Legandaria";
          } 
          if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Dragon_Infernal")){
              tipo="Legendaria";
          }
          if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Dragon")){
              tipo="Epica";
          }
          if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Gigante_Noble")){
              tipo="Comun";
          }
          if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Pandilla_Duendes")){
              tipo="Comun";
          }
          int centinela=-1;
           for (int i = 0; i < raiz.getChildCount(); i++) {
               if(raiz.getChildAt(i).toString().equals(tipo)){
                   
                   for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                       if(raiz.getChildAt(i).getChildAt(j).toString().equals(nombre) && raiz.getChildAt(i).equals(tipo)){
                       i=raiz.getChildCount();
                       j=raiz.getChildAt(i).getChildCount();
                       }
                   }
                   DefaultMutableTreeNode q = new DefaultMutableTreeNode(new Carta(nombre,dano,vida));
                   ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(q); 
                   centinela=1;
               }
           }
           if(centinela == -1){
               DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
               DefaultMutableTreeNode e = new DefaultMutableTreeNode(new Carta(nombre,dano,vida));
               n.add(e);
               raiz.add(n);
           }
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jt_cartasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cartasMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown()){
            int row = jt_cartas.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_cartas.setSelectionRow(row);
            Object v1 = jt_cartas.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if(nodo_seleccionado.getUserObject() instanceof Carta){
                carta_seleccionada = (Carta)nodo_seleccionado.getUserObject();
                menu_pop.show(evt.getComponent(),evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_jt_cartasMouseClicked

    private void jmi_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verActionPerformed
        // TODO add your handling code here:
        String nombre="";
        String vida="";
        String tipo="";
        String objetivo="";
        String dano="";
        String elixir="";
        String velocidad="";
        String ataque="";
        dano=((Carta)lista2.get(cb_mazos.getSelectedIndex())).getDano();
           vida = ((Carta)lista2.get(cb_mazos.getSelectedIndex())).getVida();
           nombre = ((Carta)lista2.get(cb_mazos.getSelectedIndex())).getNombre();
           objetivo=((Carta)lista2.get(cb_mazos.getSelectedIndex())).getObjetivo();
           elixir =((Carta)lista2.get(cb_mazos.getSelectedIndex())).getElixir();
           velocidad =((Carta)lista2.get(cb_mazos.getSelectedIndex())).getVelocidad();
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Minitekka")){
            tipo = "Especial";
            ataque="Minitekka";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")){
            tipo="Especial";
            ataque="Montapuerco";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Golem")){
            tipo = "Epica";
            ataque = "Golem";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Lenador")){
            tipo="Legendaria";
            ataque="Leñador";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Dragon_Infernal")){
            ataque="Dragon Infernal";
            tipo="Legendaria";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Dragon")){
            ataque="Dragon";
            tipo="Epica";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Gigante_Noble")){
            ataque="Gigante Noble";
            tipo="Comun";
        }
        if(cb_mazos.getSelectedItem().getClass().getSimpleName().equals("Pandilla_Duendes")){
            tipo="Pandilla de duendes";
            tipo="Comun";
        }
        JOptionPane.showMessageDialog(jd_vercartas, "Tipo ="+tipo+"\nAtaque= "+ataque+"\nDaño = "+dano+"\nPuntos de vida= "+vida+"\nNomnbre = "+nombre+"\nObjetivos = "+objetivo+"\nVelocidad = "+velocidad+"\nElixir = "+elixir);
    }//GEN-LAST:event_jmi_verActionPerformed

    private void jmi_vercartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_vercartasActionPerformed
        // TODO add your handling code here:
        jd_vercartas.setModal(true);
        jd_vercartas.pack();
        jd_vercartas.setLocationRelativeTo(this);
        jd_vercartas.setVisible(true);
    }//GEN-LAST:event_jmi_vercartasActionPerformed
    private void hola() {
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Crear;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JComboBox<String> cb_carta1;
    private javax.swing.JComboBox<String> cb_carta2;
    private javax.swing.JComboBox<String> cb_carta3;
    private javax.swing.JComboBox<String> cb_clanes;
    private javax.swing.JComboBox<String> cb_clanes1;
    private javax.swing.JComboBox<String> cb_clantipo;
    private javax.swing.JComboBox<String> cb_lider;
    private javax.swing.JComboBox<String> cb_mazo1;
    private javax.swing.JComboBox<String> cb_mazo2;
    private javax.swing.JComboBox<String> cb_mazo3;
    private javax.swing.JComboBox<String> cb_mazos;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_usuarios1;
    private javax.swing.JComboBox<String> cb_usuarios2;
    private javax.swing.JComboBox<String> cb_usuarios5;
    private javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_clancrear;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crearmazo;
    private javax.swing.JDialog jd_agregaralclan;
    private javax.swing.JDialog jd_agregarmazo;
    private javax.swing.JDialog jd_amigos_clan;
    private javax.swing.JDialog jd_crearcarta;
    private javax.swing.JDialog jd_crearclan;
    private javax.swing.JDialog jd_crearmazo;
    private javax.swing.JDialog jd_crearusa;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private com.toedter.calendar.JDateChooser jd_fecha1;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_vercartas;
    private javax.swing.JList<String> jl_lista1;
    private javax.swing.JMenuItem jmi_agregarclan;
    private javax.swing.JMenuItem jmi_agregarmazo;
    private javax.swing.JMenuItem jmi_crear;
    private javax.swing.JMenuItem jmi_crearcarta;
    private javax.swing.JMenuItem jmi_crearclan;
    private javax.swing.JMenuItem jmi_crearmazo;
    private javax.swing.JMenuItem jmi_login;
    private javax.swing.JMenuItem jmi_ver;
    private javax.swing.JMenuItem jmi_vercartas;
    private javax.swing.JMenuItem jmi_verclan;
    private javax.swing.JTextField jt_apellido;
    private javax.swing.JTree jt_cartas;
    private javax.swing.JTextField jt_contrasena;
    private javax.swing.JTextField jt_coste;
    private javax.swing.JTextField jt_dano;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombre2;
    private javax.swing.JTextField jt_nombreclan;
    private javax.swing.JTextField jt_nombreusa;
    private javax.swing.JTextField jt_puntos;
    private javax.swing.JPopupMenu menu_pop;
    private javax.swing.JPasswordField pf_passpord;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuarios> lista = new ArrayList();
    ArrayList<Mazos> lista1 = new ArrayList();
    ArrayList<Carta> lista2 = new ArrayList();
    ArrayList<Clan> lista3 = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Carta carta_seleccionada;
}
